park_indefinitely:
  description: "Park the automower indefinitely."
  target:
    entity:
      domain: "lawn_mower"

resume_schedule:
  description: "Resume the automower's schedule."
  target:
    entity:
      domain: "lawn_mower"