park_indefinitely:
  target:
    entity:
      integration: "husqvarna_automower_ble"
      domain: "lawn_mower"

resume_schedule:
  target:
    entity:
      integration: "husqvarna_automower_ble"
      domain: "lawn_mower"
